// ========================================== //
// Developer: Yohanes Wahyu Nurcahyo          //
// Website: https://github.com/yoyokits       //
// ========================================== //

namespace WorldMapControls.Extensions
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using WorldMapControls.Models.Enums;

    public static class CountryCodeExtensions
    {
        #region Fields

        // COMPREHENSIVE CountryCode to Country name mapping
        private static readonly Dictionary<CountryCode, string> CountryCodeToName = new()
        {
            // A
            { CountryCode.AD, "Andorra" },
            { CountryCode.AE, "United Arab Emirates" },
            { CountryCode.AF, "Afghanistan" },
            { CountryCode.AG, "Antigua and Barbuda" },
            { CountryCode.AI, "Anguilla" },
            { CountryCode.AL, "Albania" },
            { CountryCode.AM, "Armenia" },
            { CountryCode.AO, "Angola" },
            { CountryCode.AQ, "Antarctica" },
            { CountryCode.AR, "Argentina" },
            { CountryCode.AS, "American Samoa" },
            { CountryCode.AT, "Austria" },
            { CountryCode.AU, "Australia" },
            { CountryCode.AW, "Aruba" },
            { CountryCode.AX, "Åland Islands" },
            { CountryCode.AZ, "Azerbaijan" },

            // B
            { CountryCode.BA, "Bosnia and Herzegovina" },
            { CountryCode.BB, "Barbados" },
            { CountryCode.BD, "Bangladesh" },
            { CountryCode.BE, "Belgium" },
            { CountryCode.BF, "Burkina Faso" },
            { CountryCode.BG, "Bulgaria" },
            { CountryCode.BH, "Bahrain" },
            { CountryCode.BI, "Burundi" },
            { CountryCode.BJ, "Benin" },
            { CountryCode.BL, "Saint Barthélemy" },
            { CountryCode.BM, "Bermuda" },
            { CountryCode.BN, "Brunei Darussalam" },
            { CountryCode.BO, "Bolivia" },
            { CountryCode.BQ, "Bonaire, Sint Eustatius and Saba" },
            { CountryCode.BR, "Brazil" },
            { CountryCode.BS, "Bahamas" },
            { CountryCode.BT, "Bhutan" },
            { CountryCode.BV, "Bouvet Island" },
            { CountryCode.BW, "Botswana" },
            { CountryCode.BY, "Belarus" },
            { CountryCode.BZ, "Belize" },

            // C
            { CountryCode.CA, "Canada" },
            { CountryCode.CC, "Cocos Islands" },
            { CountryCode.CD, "Democratic Republic of the Congo" },
            { CountryCode.CF, "Central African Republic" },
            { CountryCode.CG, "Republic of the Congo" },
            { CountryCode.CH, "Switzerland" },
            { CountryCode.CI, "Côte d'Ivoire" },
            { CountryCode.CK, "Cook Islands" },
            { CountryCode.CL, "Chile" },
            { CountryCode.CM, "Cameroon" },
            { CountryCode.CN, "China" },
            { CountryCode.CO, "Colombia" },
            { CountryCode.CR, "Costa Rica" },
            { CountryCode.CU, "Cuba" },
            { CountryCode.CV, "Cabo Verde" },
            { CountryCode.CW, "Curaçao" },
            { CountryCode.CX, "Christmas Island" },
            { CountryCode.CY, "Cyprus" },
            { CountryCode.CZ, "Czech Republic" },

            // D
            { CountryCode.DE, "Germany" },
            { CountryCode.DJ, "Djibouti" },
            { CountryCode.DK, "Denmark" },
            { CountryCode.DM, "Dominica" },
            { CountryCode.DO, "Dominican Republic" },
            { CountryCode.DZ, "Algeria" },

            // E
            { CountryCode.EC, "Ecuador" },
            { CountryCode.EE, "Estonia" },
            { CountryCode.EG, "Egypt" },
            { CountryCode.EH, "Western Sahara" },
            { CountryCode.ER, "Eritrea" },
            { CountryCode.ES, "Spain" },
            { CountryCode.ET, "Ethiopia" },

            // F
            { CountryCode.FI, "Finland" },
            { CountryCode.FJ, "Fiji" },
            { CountryCode.FK, "Falkland Islands" },
            { CountryCode.FM, "Micronesia" },
            { CountryCode.FO, "Faroe Islands" },
            { CountryCode.FR, "France" },

            // G
            { CountryCode.GA, "Gabon" },
            { CountryCode.GB, "United Kingdom" },
            { CountryCode.GD, "Grenada" },
            { CountryCode.GE, "Georgia" },
            { CountryCode.GF, "French Guiana" },
            { CountryCode.GG, "Guernsey" },
            { CountryCode.GH, "Ghana" },
            { CountryCode.GI, "Gibraltar" },
            { CountryCode.GL, "Greenland" },
            { CountryCode.GM, "Gambia" },
            { CountryCode.GN, "Guinea" },
            { CountryCode.GP, "Guadeloupe" },
            { CountryCode.GQ, "Equatorial Guinea" },
            { CountryCode.GR, "Greece" },
            { CountryCode.GS, "South Georgia and South Sandwich Islands" },
            { CountryCode.GT, "Guatemala" },
            { CountryCode.GU, "Guam" },
            { CountryCode.GW, "Guinea-Bissau" },
            { CountryCode.GY, "Guyana" },

            // H
            { CountryCode.HK, "Hong Kong" },
            { CountryCode.HM, "Heard Island and McDonald Islands" },
            { CountryCode.HN, "Honduras" },
            { CountryCode.HR, "Croatia" },
            { CountryCode.HT, "Haiti" },
            { CountryCode.HU, "Hungary" },

            // I
            { CountryCode.ID, "Indonesia" },
            { CountryCode.IE, "Ireland" },
            { CountryCode.IL, "Israel" },
            { CountryCode.IM, "Isle of Man" },
            { CountryCode.IN, "India" },
            { CountryCode.IO, "British Indian Ocean Territory" },
            { CountryCode.IQ, "Iraq" },
            { CountryCode.IR, "Iran" },
            { CountryCode.IS, "Iceland" },
            { CountryCode.IT, "Italy" },

            // J
            { CountryCode.JE, "Jersey" },
            { CountryCode.JM, "Jamaica" },
            { CountryCode.JO, "Jordan" },
            { CountryCode.JP, "Japan" },

            // K
            { CountryCode.KE, "Kenya" },
            { CountryCode.KG, "Kyrgyzstan" },
            { CountryCode.KH, "Cambodia" },
            { CountryCode.KI, "Kiribati" },
            { CountryCode.KM, "Comoros" },
            { CountryCode.KN, "Saint Kitts and Nevis" },
            { CountryCode.KP, "North Korea" },
            { CountryCode.KR, "South Korea" },
            { CountryCode.KW, "Kuwait" },
            { CountryCode.KY, "Cayman Islands" },
            { CountryCode.KZ, "Kazakhstan" },

            // L
            { CountryCode.LA, "Lao People's Democratic Republic" },
            { CountryCode.LB, "Lebanon" },
            { CountryCode.LC, "Saint Lucia" },
            { CountryCode.LI, "Liechtenstein" },
            { CountryCode.LK, "Sri Lanka" },
            { CountryCode.LR, "Liberia" },
            { CountryCode.LS, "Lesotho" },
            { CountryCode.LT, "Lithuania" },
            { CountryCode.LU, "Luxembourg" },
            { CountryCode.LV, "Latvia" },
            { CountryCode.LY, "Libya" },

            // M
            { CountryCode.MA, "Morocco" },
            { CountryCode.MC, "Monaco" },
            { CountryCode.MD, "Moldova" },
            { CountryCode.ME, "Montenegro" },
            { CountryCode.MF, "Saint Martin" },
            { CountryCode.MG, "Madagascar" },
            { CountryCode.MH, "Marshall Islands" },
            { CountryCode.MK, "North Macedonia" },
            { CountryCode.ML, "Mali" },
            { CountryCode.MM, "Myanmar" },
            { CountryCode.MN, "Mongolia" },
            { CountryCode.MO, "Macao" },
            { CountryCode.MP, "Northern Mariana Islands" },
            { CountryCode.MQ, "Martinique" },
            { CountryCode.MR, "Mauritania" },
            { CountryCode.MS, "Montserrat" },
            { CountryCode.MT, "Malta" },
            { CountryCode.MU, "Mauritius" },
            { CountryCode.MV, "Maldives" },
            { CountryCode.MW, "Malawi" },
            { CountryCode.MX, "Mexico" },
            { CountryCode.MY, "Malaysia" },
            { CountryCode.MZ, "Mozambique" },

            // N
            { CountryCode.NA, "Namibia" },
            { CountryCode.NC, "New Caledonia" },
            { CountryCode.NE, "Niger" },
            { CountryCode.NF, "Norfolk Island" },
            { CountryCode.NG, "Nigeria" },
            { CountryCode.NI, "Nicaragua" },
            { CountryCode.NL, "Netherlands" },
            { CountryCode.NO, "Norway" },
            { CountryCode.NP, "Nepal" },
            { CountryCode.NR, "Nauru" },
            { CountryCode.NU, "Niue" },
            { CountryCode.NZ, "New Zealand" },

            // O
            { CountryCode.OM, "Oman" },

            // P
            { CountryCode.PA, "Panama" },
            { CountryCode.PE, "Peru" },
            { CountryCode.PF, "French Polynesia" },
            { CountryCode.PG, "Papua New Guinea" },
            { CountryCode.PH, "Philippines" },
            { CountryCode.PK, "Pakistan" },
            { CountryCode.PL, "Poland" },
            { CountryCode.PM, "Saint Pierre and Miquelon" },
            { CountryCode.PN, "Pitcairn" },
            { CountryCode.PR, "Puerto Rico" },
            { CountryCode.PS, "Palestine" },
            { CountryCode.PT, "Portugal" },
            { CountryCode.PW, "Palau" },
            { CountryCode.PY, "Paraguay" },

            // Q
            { CountryCode.QA, "Qatar" },

            // R
            { CountryCode.RE, "Réunion" },
            { CountryCode.RO, "Romania" },
            { CountryCode.RS, "Serbia" },
            { CountryCode.RU, "Russian Federation" },
            { CountryCode.RW, "Rwanda" },

            // S
            { CountryCode.SA, "Saudi Arabia" },
            { CountryCode.SB, "Solomon Islands" },
            { CountryCode.SC, "Seychelles" },
            { CountryCode.SD, "Sudan" },
            { CountryCode.SE, "Sweden" },
            { CountryCode.SG, "Singapore" },
            { CountryCode.SH, "Saint Helena, Ascension and Tristan da Cunha" },
            { CountryCode.SI, "Slovenia" },
            { CountryCode.SJ, "Svalbard and Jan Mayen" },
            { CountryCode.SK, "Slovakia" },
            { CountryCode.SL, "Sierra Leone" },
            { CountryCode.SM, "San Marino" },
            { CountryCode.SN, "Senegal" },
            { CountryCode.SO, "Somalia" },
            { CountryCode.SR, "Suriname" },
            { CountryCode.SS, "South Sudan" },
            { CountryCode.ST, "Sao Tome and Principe" },
            { CountryCode.SV, "El Salvador" },
            { CountryCode.SX, "Sint Maarten" },
            { CountryCode.SY, "Syrian Arab Republic" },
            { CountryCode.SZ, "Eswatini" },

            // T
            { CountryCode.TC, "Turks and Caicos Islands" },
            { CountryCode.TD, "Chad" },
            { CountryCode.TF, "French Southern Territories" },
            { CountryCode.TG, "Togo" },
            { CountryCode.TH, "Thailand" },
            { CountryCode.TJ, "Tajikistan" },
            { CountryCode.TK, "Tokelau" },
            { CountryCode.TL, "Timor-Leste" },
            { CountryCode.TM, "Turkmenistan" },
            { CountryCode.TN, "Tunisia" },
            { CountryCode.TO, "Tonga" },
            { CountryCode.TR, "Turkey" },
            { CountryCode.TT, "Trinidad and Tobago" },
            { CountryCode.TV, "Tuvalu" },
            { CountryCode.TW, "Taiwan" },
            { CountryCode.TZ, "Tanzania" },

            // U
            { CountryCode.UA, "Ukraine" },
            { CountryCode.UG, "Uganda" },
            { CountryCode.UM, "United States Minor Outlying Islands" },
            { CountryCode.US, "United States" },
            { CountryCode.UY, "Uruguay" },
            { CountryCode.UZ, "Uzbekistan" },

            // V
            { CountryCode.VA, "Holy See" },
            { CountryCode.VC, "Saint Vincent and the Grenadines" },
            { CountryCode.VE, "Venezuela" },
            { CountryCode.VG, "Virgin Islands (British)" },
            { CountryCode.VI, "Virgin Islands (U.S.)" },
            { CountryCode.VN, "Viet Nam" },
            { CountryCode.VU, "Vanuatu" },

            // W
            { CountryCode.WF, "Wallis and Futuna" },
            { CountryCode.WS, "Samoa" },

            // Y
            { CountryCode.YE, "Yemen" },
            { CountryCode.YT, "Mayotte" },

            // Z
            { CountryCode.ZA, "South Africa" },
            { CountryCode.ZM, "Zambia" },
            { CountryCode.ZW, "Zimbabwe" },

            // Kosovo (user-assigned code)
            { CountryCode.XK, "Kosovo" }
        };

        // Country -> CountryCode mapping
        private static readonly Dictionary<Country, CountryCode> CountryToCountryCode = new()
        {
            // North America
            { Country.UnitedStates, CountryCode.US },
            { Country.Canada, CountryCode.CA },
            { Country.Mexico, CountryCode.MX },
            { Country.Greenland, CountryCode.GL },
            { Country.Guatemala, CountryCode.GT },
            { Country.Belize, CountryCode.BZ },
            { Country.ElSalvador, CountryCode.SV },
            { Country.Honduras, CountryCode.HN },
            { Country.Nicaragua, CountryCode.NI },
            { Country.CostaRica, CountryCode.CR },
            { Country.Panama, CountryCode.PA },
            { Country.Cuba, CountryCode.CU },
            { Country.Jamaica, CountryCode.JM },
            { Country.Haiti, CountryCode.HT },
            { Country.DominicanRepublic, CountryCode.DO },

            // South America
            { Country.Brazil, CountryCode.BR },
            { Country.Argentina, CountryCode.AR },
            { Country.Chile, CountryCode.CL },
            { Country.Colombia, CountryCode.CO },
            { Country.Venezuela, CountryCode.VE },
            { Country.Peru, CountryCode.PE },
            { Country.Ecuador, CountryCode.EC },
            { Country.Bolivia, CountryCode.BO },
            { Country.Paraguay, CountryCode.PY },
            { Country.Uruguay, CountryCode.UY },
            { Country.Guyana, CountryCode.GY },
            { Country.Suriname, CountryCode.SR },

            // Europe
            { Country.UnitedKingdom, CountryCode.GB },
            { Country.France, CountryCode.FR },
            { Country.Germany, CountryCode.DE },
            { Country.Italy, CountryCode.IT },
            { Country.Spain, CountryCode.ES },
            { Country.Portugal, CountryCode.PT },
            { Country.Netherlands, CountryCode.NL },
            { Country.Belgium, CountryCode.BE },
            { Country.Switzerland, CountryCode.CH },
            { Country.Austria, CountryCode.AT },
            { Country.Sweden, CountryCode.SE },
            { Country.Norway, CountryCode.NO },
            { Country.Finland, CountryCode.FI },
            { Country.Denmark, CountryCode.DK },
            { Country.Poland, CountryCode.PL },
            { Country.Russia, CountryCode.RU },
            { Country.Ukraine, CountryCode.UA },
            { Country.Turkey, CountryCode.TR },
            { Country.Greece, CountryCode.GR },
            { Country.Romania, CountryCode.RO },
            { Country.Bulgaria, CountryCode.BG },
            { Country.Hungary, CountryCode.HU },
            { Country.CzechRepublic, CountryCode.CZ },
            { Country.Slovakia, CountryCode.SK },
            { Country.Slovenia, CountryCode.SI },
            { Country.Croatia, CountryCode.HR },
            { Country.Serbia, CountryCode.RS },
            { Country.Montenegro, CountryCode.ME },
            { Country.BosniaAndHerzegovina, CountryCode.BA },
            { Country.NorthMacedonia, CountryCode.MK },
            { Country.Albania, CountryCode.AL },
            { Country.Estonia, CountryCode.EE },
            { Country.Latvia, CountryCode.LV },
            { Country.Lithuania, CountryCode.LT },
            { Country.Belarus, CountryCode.BY },
            { Country.Moldova, CountryCode.MD },
            { Country.Azerbaijan, CountryCode.AZ },
            { Country.Iceland, CountryCode.IS },
            { Country.Ireland, CountryCode.IE },
            { Country.Georgia, CountryCode.GE },
            { Country.Armenia, CountryCode.AM },
            { Country.Kosovo, CountryCode.XK },

            // Asia
            { Country.China, CountryCode.CN },
            { Country.Japan, CountryCode.JP },
            { Country.SouthKorea, CountryCode.KR },
            { Country.NorthKorea, CountryCode.KP },
            { Country.India, CountryCode.IN },
            { Country.Indonesia, CountryCode.ID },
            { Country.Vietnam, CountryCode.VN },
            { Country.Thailand, CountryCode.TH },
            { Country.Malaysia, CountryCode.MY },
            { Country.Singapore, CountryCode.SG },
            { Country.Philippines, CountryCode.PH },
            { Country.Myanmar, CountryCode.MM },
            { Country.Cambodia, CountryCode.KH },
            { Country.Laos, CountryCode.LA },
            { Country.Bangladesh, CountryCode.BD },
            { Country.Pakistan, CountryCode.PK },
            { Country.Afghanistan, CountryCode.AF },
            { Country.Nepal, CountryCode.NP },
            { Country.Bhutan, CountryCode.BT },
            { Country.SriLanka, CountryCode.LK },
            { Country.Maldives, CountryCode.MV },
            { Country.Mongolia, CountryCode.MN },
            { Country.Kazakhstan, CountryCode.KZ },
            { Country.Uzbekistan, CountryCode.UZ },
            { Country.Turkmenistan, CountryCode.TM },
            { Country.Kyrgyzstan, CountryCode.KG },
            { Country.Tajikistan, CountryCode.TJ },
            { Country.TimorLeste, CountryCode.TL },

            // Middle East
            { Country.SaudiArabia, CountryCode.SA },
            { Country.Iran, CountryCode.IR },
            { Country.Iraq, CountryCode.IQ },
            { Country.Israel, CountryCode.IL },
            { Country.Palestine, CountryCode.PS },
            { Country.Jordan, CountryCode.JO },
            { Country.Lebanon, CountryCode.LB },
            { Country.Syria, CountryCode.SY },
            { Country.Yemen, CountryCode.YE },
            { Country.Oman, CountryCode.OM },
            { Country.UAE, CountryCode.AE },
            { Country.Qatar, CountryCode.QA },
            { Country.Bahrain, CountryCode.BH },
            { Country.Kuwait, CountryCode.KW },

            // Africa
            { Country.SouthAfrica, CountryCode.ZA },
            { Country.Egypt, CountryCode.EG },
            { Country.Nigeria, CountryCode.NG },
            { Country.Kenya, CountryCode.KE },
            { Country.Ethiopia, CountryCode.ET },
            { Country.Tanzania, CountryCode.TZ },
            { Country.Uganda, CountryCode.UG },
            { Country.Rwanda, CountryCode.RW },
            { Country.Burundi, CountryCode.BI },
            { Country.DemocraticRepublicOfCongo, CountryCode.CD },
            { Country.RepublicOfCongo, CountryCode.CG },
            { Country.CentralAfricanRepublic, CountryCode.CF },
            { Country.Chad, CountryCode.TD },
            { Country.Sudan, CountryCode.SD },
            { Country.SouthSudan, CountryCode.SS },
            { Country.Libya, CountryCode.LY },
            { Country.Tunisia, CountryCode.TN },
            { Country.Algeria, CountryCode.DZ },
            { Country.Morocco, CountryCode.MA },
            { Country.Ghana, CountryCode.GH },
            { Country.IvoryCoast, CountryCode.CI },
            { Country.BurkinaFaso, CountryCode.BF },
            { Country.Mali, CountryCode.ML },
            { Country.Niger, CountryCode.NE },
            { Country.Senegal, CountryCode.SN },
            { Country.Guinea, CountryCode.GN },
            { Country.SierraLeone, CountryCode.SL },
            { Country.Liberia, CountryCode.LR },
            { Country.Gambia, CountryCode.GM },
            { Country.GuineaBissau, CountryCode.GW },
            { Country.Mauritania, CountryCode.MR },
            { Country.Madagascar, CountryCode.MG },
            { Country.Mozambique, CountryCode.MZ },
            { Country.Zimbabwe, CountryCode.ZW },
            { Country.Botswana, CountryCode.BW },
            { Country.Namibia, CountryCode.NA },
            { Country.Zambia, CountryCode.ZM },
            { Country.Malawi, CountryCode.MW },
            { Country.Angola, CountryCode.AO },
            { Country.Cameroon, CountryCode.CM },
            { Country.EquatorialGuinea, CountryCode.GQ },
            { Country.Gabon, CountryCode.GA },
            { Country.SaoTomeAndPrincipe, CountryCode.ST },
            { Country.Somalia, CountryCode.SO },
            { Country.Lesotho, CountryCode.LS },
            { Country.Eswatini, CountryCode.SZ },
            { Country.Benin, CountryCode.BJ },
            { Country.Togo, CountryCode.TG },
            { Country.Djibouti, CountryCode.DJ },
            { Country.Eritrea, CountryCode.ER },

            // Oceania
            { Country.Australia, CountryCode.AU },
            { Country.NewZealand, CountryCode.NZ },
            { Country.FijiIslands, CountryCode.FJ },
            { Country.PapuaNewGuinea, CountryCode.PG },
            { Country.SolomonIslands, CountryCode.SB },
            { Country.Vanuatu, CountryCode.VU },
            { Country.NewCaledonia, CountryCode.NC },
            { Country.Samoa, CountryCode.WS },
            { Country.Tonga, CountryCode.TO },
            { Country.Palau, CountryCode.PW },
            { Country.MarshallIslands, CountryCode.MH },
            { Country.Micronesia, CountryCode.FM },
            { Country.Kiribati, CountryCode.KI },
            { Country.Nauru, CountryCode.NR },
            { Country.Tuvalu, CountryCode.TV },

            // Additional + territories
            { Country.Cyprus, CountryCode.CY },
            { Country.Malta, CountryCode.MT },
            { Country.Luxembourg, CountryCode.LU },
            { Country.Monaco, CountryCode.MC },
            { Country.Liechtenstein, CountryCode.LI },
            { Country.Andorra, CountryCode.AD },
            { Country.SanMarino, CountryCode.SM },
            { Country.VaticanCity, CountryCode.VA },
            { Country.Comoros, CountryCode.KM },
            { Country.Seychelles, CountryCode.SC },
            { Country.Mauritius, CountryCode.MU },
            { Country.CaboVerde, CountryCode.CV },
            { Country.Barbados, CountryCode.BB },
            { Country.Trinidad, CountryCode.TT },
            { Country.Grenada, CountryCode.GD },
            { Country.StLucia, CountryCode.LC },
            { Country.StVincent, CountryCode.VC },
            { Country.Dominica, CountryCode.DM },
            { Country.AntiguaBarbuda, CountryCode.AG },
            { Country.StKittsNevis, CountryCode.KN },
            { Country.Bahamas, CountryCode.BS },
            { Country.Brunei, CountryCode.BN },
            { Country.Anguilla, CountryCode.AI },
            { Country.Antarctica, CountryCode.AQ },
            { Country.AmericanSamoa, CountryCode.AS },
            { Country.Aruba, CountryCode.AW },
            { Country.AlandIslands, CountryCode.AX },
            { Country.SaintBarthelemy, CountryCode.BL },
            { Country.Bermuda, CountryCode.BM },
            { Country.BonaireSintEustatiusAndSaba, CountryCode.BQ },
            { Country.BouvetIsland, CountryCode.BV },
            { Country.CocosIslands, CountryCode.CC },
            { Country.CookIslands, CountryCode.CK },
            { Country.Curacao, CountryCode.CW },
            { Country.ChristmasIsland, CountryCode.CX },
            { Country.WesternSahara, CountryCode.EH },
            { Country.FalklandIslands, CountryCode.FK },
            { Country.FaroeIslands, CountryCode.FO },
            { Country.FrenchGuiana, CountryCode.GF },
            { Country.Guernsey, CountryCode.GG },
            { Country.Gibraltar, CountryCode.GI },
            { Country.Guadeloupe, CountryCode.GP },
            { Country.SouthGeorgiaAndSouthSandwichIslands, CountryCode.GS },
            { Country.Guam, CountryCode.GU },
            { Country.HongKong, CountryCode.HK },
            { Country.HeardIslandAndMcDonaldIslands, CountryCode.HM },
            { Country.IsleOfMan, CountryCode.IM },
            { Country.BritishIndianOceanTerritory, CountryCode.IO },
            { Country.Jersey, CountryCode.JE },
            { Country.CaymanIslands, CountryCode.KY },
            { Country.SaintMartin, CountryCode.MF },
            { Country.Macao, CountryCode.MO },
            { Country.NorthernMarianaIslands, CountryCode.MP },
            { Country.Martinique, CountryCode.MQ },
            { Country.Montserrat, CountryCode.MS },
            { Country.NorfolkIsland, CountryCode.NF },
            { Country.Niue, CountryCode.NU },
            { Country.FrenchPolynesia, CountryCode.PF },
            { Country.SaintPierreAndMiquelon, CountryCode.PM },
            { Country.Pitcairn, CountryCode.PN },
            { Country.PuertoRico, CountryCode.PR },
            { Country.Reunion, CountryCode.RE },
            { Country.SaintHelenaAscensionAndTristanDaCunha, CountryCode.SH },
            { Country.SvalbardAndJanMayen, CountryCode.SJ },
            { Country.SintMaarten, CountryCode.SX },
            { Country.TurksAndCaicosIslands, CountryCode.TC },
            { Country.FrenchSouthernTerritories, CountryCode.TF },
            { Country.Tokelau, CountryCode.TK },
            { Country.Taiwan, CountryCode.TW },
            { Country.UnitedStatesMinorOutlyingIslands, CountryCode.UM },
            { Country.VirginIslandsBritish, CountryCode.VG },
            { Country.VirginIslandsUS, CountryCode.VI },
            { Country.WallisAndFutuna, CountryCode.WF },
            { Country.Mayotte, CountryCode.YT }
        };

        // Reverse mapping
        private static readonly Dictionary<CountryCode, Country> CountryCodeToCountry = new()
        {
            { CountryCode.US, Country.UnitedStates },
            { CountryCode.CA, Country.Canada },
            { CountryCode.MX, Country.Mexico },
            { CountryCode.GL, Country.Greenland },
            { CountryCode.GT, Country.Guatemala },
            { CountryCode.BZ, Country.Belize },
            { CountryCode.SV, Country.ElSalvador },
            { CountryCode.HN, Country.Honduras },
            { CountryCode.NI, Country.Nicaragua },
            { CountryCode.CR, Country.CostaRica },
            { CountryCode.PA, Country.Panama },
            { CountryCode.CU, Country.Cuba },
            { CountryCode.JM, Country.Jamaica },
            { CountryCode.HT, Country.Haiti },
            { CountryCode.DO, Country.DominicanRepublic },
            { CountryCode.BR, Country.Brazil },
            { CountryCode.AR, Country.Argentina },
            { CountryCode.CL, Country.Chile },
            { CountryCode.CO, Country.Colombia },
            { CountryCode.VE, Country.Venezuela },
            { CountryCode.PE, Country.Peru },
            { CountryCode.EC, Country.Ecuador },
            { CountryCode.BO, Country.Bolivia },
            { CountryCode.PY, Country.Paraguay },
            { CountryCode.UY, Country.Uruguay },
            { CountryCode.GY, Country.Guyana },
            { CountryCode.SR, Country.Suriname },
            { CountryCode.GB, Country.UnitedKingdom },
            { CountryCode.FR, Country.France },
            { CountryCode.DE, Country.Germany },
            { CountryCode.IT, Country.Italy },
            { CountryCode.ES, Country.Spain },
            { CountryCode.PT, Country.Portugal },
            { CountryCode.NL, Country.Netherlands },
            { CountryCode.BE, Country.Belgium },
            { CountryCode.CH, Country.Switzerland },
            { CountryCode.AT, Country.Austria },
            { CountryCode.SE, Country.Sweden },
            { CountryCode.NO, Country.Norway },
            { CountryCode.FI, Country.Finland },
            { CountryCode.DK, Country.Denmark },
            { CountryCode.PL, Country.Poland },
            { CountryCode.RU, Country.Russia },
            { CountryCode.UA, Country.Ukraine },
            { CountryCode.TR, Country.Turkey },
            { CountryCode.GR, Country.Greece },
            { CountryCode.RO, Country.Romania },
            { CountryCode.BG, Country.Bulgaria },
            { CountryCode.HU, Country.Hungary },
            { CountryCode.CZ, Country.CzechRepublic },
            { CountryCode.SK, Country.Slovakia },
            { CountryCode.SI, Country.Slovenia },
            { CountryCode.HR, Country.Croatia },
            { CountryCode.RS, Country.Serbia },
            { CountryCode.ME, Country.Montenegro },
            { CountryCode.BA, Country.BosniaAndHerzegovina },
            { CountryCode.MK, Country.NorthMacedonia },
            { CountryCode.AL, Country.Albania },
            { CountryCode.EE, Country.Estonia },
            { CountryCode.LV, Country.Latvia },
            { CountryCode.LT, Country.Lithuania },
            { CountryCode.BY, Country.Belarus },
            { CountryCode.MD, Country.Moldova },
            { CountryCode.AZ, Country.Azerbaijan },
            { CountryCode.IS, Country.Iceland },
            { CountryCode.IE, Country.Ireland },
            { CountryCode.GE, Country.Georgia },
            { CountryCode.AM, Country.Armenia },
            { CountryCode.XK, Country.Kosovo },
            { CountryCode.CN, Country.China },
            { CountryCode.JP, Country.Japan },
            { CountryCode.KR, Country.SouthKorea },
            { CountryCode.KP, Country.NorthKorea },
            { CountryCode.IN, Country.India },
            { CountryCode.ID, Country.Indonesia },
            { CountryCode.VN, Country.Vietnam },
            { CountryCode.TH, Country.Thailand },
            { CountryCode.MY, Country.Malaysia },
            { CountryCode.SG, Country.Singapore },
            { CountryCode.PH, Country.Philippines },
            { CountryCode.MM, Country.Myanmar },
            { CountryCode.KH, Country.Cambodia },
            { CountryCode.LA, Country.Laos },
            { CountryCode.BD, Country.Bangladesh },
            { CountryCode.PK, Country.Pakistan },
            { CountryCode.AF, Country.Afghanistan },
            { CountryCode.NP, Country.Nepal },
            { CountryCode.BT, Country.Bhutan },
            { CountryCode.LK, Country.SriLanka },
            { CountryCode.MV, Country.Maldives },
            { CountryCode.MN, Country.Mongolia },
            { CountryCode.KZ, Country.Kazakhstan },
            { CountryCode.UZ, Country.Uzbekistan },
            { CountryCode.TM, Country.Turkmenistan },
            { CountryCode.KG, Country.Kyrgyzstan },
            { CountryCode.TJ, Country.Tajikistan },
            { CountryCode.TL, Country.TimorLeste },
            { CountryCode.SA, Country.SaudiArabia },
            { CountryCode.IR, Country.Iran },
            { CountryCode.IQ, Country.Iraq },
            { CountryCode.IL, Country.Israel },
            { CountryCode.PS, Country.Palestine },
            { CountryCode.JO, Country.Jordan },
            { CountryCode.LB, Country.Lebanon },
            { CountryCode.SY, Country.Syria },
            { CountryCode.YE, Country.Yemen },
            { CountryCode.OM, Country.Oman },
            { CountryCode.AE, Country.UAE },
            { CountryCode.QA, Country.Qatar },
            { CountryCode.BH, Country.Bahrain },
            { CountryCode.KW, Country.Kuwait },
            { CountryCode.ZA, Country.SouthAfrica },
            { CountryCode.EG, Country.Egypt },
            { CountryCode.NG, Country.Nigeria },
            { CountryCode.KE, Country.Kenya },
            { CountryCode.ET, Country.Ethiopia },
            { CountryCode.TZ, Country.Tanzania },
            { CountryCode.UG, Country.Uganda },
            { CountryCode.RW, Country.Rwanda },
            { CountryCode.BI, Country.Burundi },
            { CountryCode.CD, Country.DemocraticRepublicOfCongo },
            { CountryCode.CG, Country.RepublicOfCongo },
            { CountryCode.CF, Country.CentralAfricanRepublic },
            { CountryCode.TD, Country.Chad },
            { CountryCode.SD, Country.Sudan },
            { CountryCode.SS, Country.SouthSudan },
            { CountryCode.LY, Country.Libya },
            { CountryCode.TN, Country.Tunisia },
            { CountryCode.DZ, Country.Algeria },
            { CountryCode.MA, Country.Morocco },
            { CountryCode.GH, Country.Ghana },
            { CountryCode.CI, Country.IvoryCoast },
            { CountryCode.BF, Country.BurkinaFaso },
            { CountryCode.ML, Country.Mali },
            { CountryCode.NE, Country.Niger },
            { CountryCode.SN, Country.Senegal },
            { CountryCode.GN, Country.Guinea },
            { CountryCode.SL, Country.SierraLeone },
            { CountryCode.LR, Country.Liberia },
            { CountryCode.GM, Country.Gambia },
            { CountryCode.GW, Country.GuineaBissau },
            { CountryCode.MR, Country.Mauritania },
            { CountryCode.MG, Country.Madagascar },
            { CountryCode.MZ, Country.Mozambique },
            { CountryCode.ZW, Country.Zimbabwe },
            { CountryCode.BW, Country.Botswana },
            { CountryCode.NA, Country.Namibia },
            { CountryCode.ZM, Country.Zambia },
            { CountryCode.MW, Country.Malawi },
            { CountryCode.AO, Country.Angola },
            { CountryCode.CM, Country.Cameroon },
            { CountryCode.GQ, Country.EquatorialGuinea },
            { CountryCode.GA, Country.Gabon },
            { CountryCode.ST, Country.SaoTomeAndPrincipe },
            { CountryCode.SO, Country.Somalia },
            { CountryCode.LS, Country.Lesotho },
            { CountryCode.SZ, Country.Eswatini },
            { CountryCode.BJ, Country.Benin },
            { CountryCode.TG, Country.Togo },
            { CountryCode.DJ, Country.Djibouti },
            { CountryCode.ER, Country.Eritrea },
            { CountryCode.AU, Country.Australia },
            { CountryCode.NZ, Country.NewZealand },
            { CountryCode.FJ, Country.FijiIslands },
            { CountryCode.PG, Country.PapuaNewGuinea },
            { CountryCode.SB, Country.SolomonIslands },
            { CountryCode.VU, Country.Vanuatu },
            { CountryCode.NC, Country.NewCaledonia },
            { CountryCode.WS, Country.Samoa },
            { CountryCode.TO, Country.Tonga },
            { CountryCode.PW, Country.Palau },
            { CountryCode.MH, Country.MarshallIslands },
            { CountryCode.FM, Country.Micronesia },
            { CountryCode.KI, Country.Kiribati },
            { CountryCode.NR, Country.Nauru },
            { CountryCode.TV, Country.Tuvalu },
            { CountryCode.CY, Country.Cyprus },
            { CountryCode.MT, Country.Malta },
            { CountryCode.LU, Country.Luxembourg },
            { CountryCode.MC, Country.Monaco },
            { CountryCode.LI, Country.Liechtenstein },
            { CountryCode.AD, Country.Andorra },
            { CountryCode.SM, Country.SanMarino },
            { CountryCode.VA, Country.VaticanCity },
            { CountryCode.KM, Country.Comoros },
            { CountryCode.SC, Country.Seychelles },
            { CountryCode.MU, Country.Mauritius },
            { CountryCode.CV, Country.CaboVerde },
            { CountryCode.BB, Country.Barbados },
            { CountryCode.TT, Country.Trinidad },
            { CountryCode.GD, Country.Grenada },
            { CountryCode.LC, Country.StLucia },
            { CountryCode.VC, Country.StVincent },
            { CountryCode.DM, Country.Dominica },
            { CountryCode.AG, Country.AntiguaBarbuda },
            { CountryCode.KN, Country.StKittsNevis },
            { CountryCode.BS, Country.Bahamas },
            { CountryCode.BN, Country.Brunei },
            { CountryCode.AI, Country.Anguilla },
            { CountryCode.AQ, Country.Antarctica },
            { CountryCode.AS, Country.AmericanSamoa },
            { CountryCode.AW, Country.Aruba },
            { CountryCode.AX, Country.AlandIslands },
            { CountryCode.BL, Country.SaintBarthelemy },
            { CountryCode.BM, Country.Bermuda },
            { CountryCode.BQ, Country.BonaireSintEustatiusAndSaba },
            { CountryCode.BV, Country.BouvetIsland },
            { CountryCode.CC, Country.CocosIslands },
            { CountryCode.CK, Country.CookIslands },
            { CountryCode.CW, Country.Curacao },
            { CountryCode.CX, Country.ChristmasIsland },
            { CountryCode.EH, Country.WesternSahara },
            { CountryCode.FK, Country.FalklandIslands },
            { CountryCode.FO, Country.FaroeIslands },
            { CountryCode.GF, Country.FrenchGuiana },
            { CountryCode.GG, Country.Guernsey },
            { CountryCode.GI, Country.Gibraltar },
            { CountryCode.GP, Country.Guadeloupe },
            { CountryCode.GS, Country.SouthGeorgiaAndSouthSandwichIslands },
            { CountryCode.GU, Country.Guam },
            { CountryCode.HK, Country.HongKong },
            { CountryCode.HM, Country.HeardIslandAndMcDonaldIslands },
            { CountryCode.IM, Country.IsleOfMan },
            { CountryCode.IO, Country.BritishIndianOceanTerritory },
            { CountryCode.JE, Country.Jersey },
            { CountryCode.KY, Country.CaymanIslands },
            { CountryCode.MF, Country.SaintMartin },
            { CountryCode.MO, Country.Macao },
            { CountryCode.MP, Country.NorthernMarianaIslands },
            { CountryCode.MQ, Country.Martinique },
            { CountryCode.MS, Country.Montserrat },
            { CountryCode.NF, Country.NorfolkIsland },
            { CountryCode.NU, Country.Niue },
            { CountryCode.PF, Country.FrenchPolynesia },
            { CountryCode.PM, Country.SaintPierreAndMiquelon },
            { CountryCode.PN, Country.Pitcairn },
            { CountryCode.PR, Country.PuertoRico },
            { CountryCode.RE, Country.Reunion },
            { CountryCode.SH, Country.SaintHelenaAscensionAndTristanDaCunha },
            { CountryCode.SJ, Country.SvalbardAndJanMayen },
            { CountryCode.SX, Country.SintMaarten },
            { CountryCode.TC, Country.TurksAndCaicosIslands },
            { CountryCode.TF, Country.FrenchSouthernTerritories },
            { CountryCode.TK, Country.Tokelau },
            { CountryCode.TW, Country.Taiwan },
            { CountryCode.UM, Country.UnitedStatesMinorOutlyingIslands },
            { CountryCode.VG, Country.VirginIslandsBritish },
            { CountryCode.VI, Country.VirginIslandsUS },
            { CountryCode.WF, Country.WallisAndFutuna },
            { CountryCode.YT, Country.Mayotte }
        };

        #endregion Fields

        #region Methods

        public static CountryCode[] GetAllCountryCodes() =>
            Enum.GetValues<CountryCode>()
                .Where(c => c != CountryCode.Unknown)
                .OrderBy(c => c.ToString())
                .ToArray();

        public static CountryCode GetCountryCode(string countryName) =>
            CountryNameVariationsExtensions.ParseCountryName(countryName);

        public static string GetCountryName(this CountryCode countryCode) =>
            CountryCodeToName.TryGetValue(countryCode, out var name) ? name : countryCode.ToString();

        public static string ToCode(this CountryCode countryCode) =>
            countryCode == CountryCode.Unknown ? string.Empty : countryCode.ToString();

        public static Country ToCountry(this CountryCode countryCode) =>
            CountryCodeToCountry.TryGetValue(countryCode, out var c) ? c : Country.Unknown;

        public static CountryCode ToCountryCode(this Country country) =>
            CountryToCountryCode.TryGetValue(country, out var code) ? code : CountryCode.Unknown;

        #endregion Methods
    }
}